C0 = list(input().split())
C1 = list(input().split())
C2 = list(input().split())
C3 = list(input().split())
C0.reverse()
C1.reverse()
C2.reverse()
C3.reverse()
print(" ".join(C3))
print(" ".join(C2))
print(" ".join(C1))
print(" ".join(C0))